# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

# ... (其他 Airflow 設定)

airflow:
  connections:
    - conn_id: gcp_bucket
      conn_type: google_cloud_platform
      conn_extra:
        keyfile_path: /usr/local/airflow/include/keys/service_account.json
          
# ... (其他連線或設定)
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value:
